version: '3.8'

services:
  # backend:
  #   build: .
  #   ports:
  #     - "5500:5500"
  #   environment:
  #     PORT: 5500
  #     SUPABASE_URL: ${SUPABASE_URL}
  #     SUPABASE_KEY: ${SUPABASE_KEY}
  #     REDIS_URL: redis://redis:6379
  #     CRYPTO_SECRET: ${CRYPTO_SECRET}
  #     ADM: ${ADM}
  #     RPC_URL: ${RPC_URL}
  #   depends_on:
  #     - redis
  #   restart: unless-stopped
  #   healthcheck:
  #     test: [ "CMD", "curl", "-f", "http://localhost:5500/health" ]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5
  #     start_period: 5s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: [ "redis-server", "--appendonly", "yes" ]
    restart: unless-stopped

volumes:
  redis-data:
